#include "hal_data.h"
#include "debug_uart/bsp_uart.h"
#include "debug_uart/bsp_dmac.h"
#include "debug_adc/hal_adc.h"
#include "debug_dht11/dht11.h"
#include "debug_ds18b20/ds18b20.h"
#include "debug_pwm_gpt_control/pwm.h"
#include "debug_ws2812/ws2812.h"
#include <stdlib.h>
#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif
//ws2812
volatile bool g_transfer_complete  = false;
void sci_spi_callback (spi_callback_args_t * p_args)
{
    if (SPI_EVENT_TRANSFER_COMPLETE == p_args->event)
    {
      g_transfer_complete  = true;
    }
}
//判断的标志
char light[6]="true";
volatile int arrive_flag = 0;
//
Adc_Result MY_data;
uint8_t humdity_integer;//湿度整数
uint8_t humdity_decimal;//湿度小数
uint8_t temp_integer ;//温度整数
uint8_t temp_decimal ;//温度小数
uint8_t dht11_check ;//校验值
Adc_Result my_data;///adc
gyroTypeDef gyro;//imu
angleTypeDef angle;
uint8_t duty1_count = 50;
uint8_t duty2_count = 50;//pwm占空比
volatile int ceshi = 0;//测试
float temp;///温度,温湿度
float humi;
volatile int v=0;//速度
volatile int MOVE_Lock = 0;//锁定
volatile int move = 0;//移动方向
volatile int jixiebi = 0;//机械臂编号
volatile int jixiebi_value=0;//机械臂占空比
//////////uart接收以及dma储存数组
char analyze[90]={0}; 
	uint8_t sci_rx_data[size];
  uint8_t sci2_rx_data[size2];
  uint8_t sci3_rx_data[size3];
	uint8_t sci8_rx_data[size8];
	volatile uint8_t sci9_rx_data[size9];
	extern volatile bool uart_send_complete_flag;
	extern volatile uint8_t dmac_sci_tx_flag;
  extern volatile uint8_t dmac_sci_rx_flag;
  extern volatile bool uart2_send_complete_flag;
	extern volatile uint8_t dmac2_sci_tx_flag;
  extern volatile uint8_t dmac2_sci_rx_flag;
  extern volatile bool uart3_send_complete_flag;
	extern volatile uint8_t dmac3_sci_tx_flag;
  extern volatile uint8_t dmac3_sci_rx_flag;
	extern volatile bool uart8_send_complete_flag;
	extern volatile uint8_t dmac8_sci_tx_flag;
  extern volatile uint8_t dmac8_sci_rx_flag;
	extern volatile bool uart9_send_complete_flag;
	extern volatile uint8_t dmac9_sci_tx_flag;
  extern volatile uint8_t dmac9_sci_rx_flag;
///////GPS数据
volatile double GPS_LNG_USE = 0;
volatile double GPS_LAT_USE = 0;
////舵机pwm设置函数
void pwm_setdutyshang(uint8_t duty55){
	  uint32_t duty_count_A1;
    // 公式：计数值 = 总周期 * 脉宽(us) / 20000us
    duty_count_A1 = 60800 - (duty55 * 624UL)/10UL;
   
	 R_GPT_DutyCycleSet(&pwm_ctrl,duty_count_A1,GPT_IO_PIN_GTIOCA);//上下 605
	 
}
void pwm_setdutyzuo(uint8_t duty66){
	uint32_t duty_count_B2;
	 duty_count_B2 = 60800 - (duty66 * 624UL)/10UL;
	R_GPT_DutyCycleSet(&pwm_ctrl,duty_count_B2,GPT_IO_PIN_GTIOCB);//左右 106
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
	void hal_entry(void)
{
    /* TODO: add your own code here */
	/////////初始化函数
	UART2_Init();
	UART5_Init();
	UART3_Init();
	UART8_Init();
	UART9_Init();
	R_ICU->IELSR[SCI2_RXI_IRQn]=0U;
	R_ICU->IELSR[SCI5_RXI_IRQn]=0U;
  R_ICU->IELSR[SCI3_RXI_IRQn]=0U;
  R_ICU->IELSR[SCI8_RXI_IRQn]=0U;  		
	R_ICU->IELSR[SCI9_RXI_IRQn]=0U; 
	set_transfer_dst_src_address(g_transfer_dmac_rx.p_cfg,&R_SCI5->RDR,&sci_rx_data[0]);
	set_transfer2_dst_src_address(g2_transfer_dmac_rx.p_cfg,&R_SCI2->RDR,&sci2_rx_data[0]);
	set_transfer3_dst_src_address(g3_transfer_dmac_rx.p_cfg,&R_SCI3->RDR,&sci3_rx_data[0]);
	set_transfer3_dst_src_address(g8_transfer_dmac_rx.p_cfg,&R_SCI8->RDR,&sci8_rx_data[0]);
	set_transfer3_dst_src_address(g9_transfer_dmac_rx.p_cfg,&R_SCI9->RDR,&sci9_rx_data[0]);
	set_transfer_length(g_transfer_dmac_rx.p_cfg,size);
	set_transfer2_length(g2_transfer_dmac_rx.p_cfg,size2);
	set_transfer3_length(g3_transfer_dmac_rx.p_cfg,size3);
	set_transfer3_length(g8_transfer_dmac_rx.p_cfg,size8);
	set_transfer3_length(g9_transfer_dmac_rx.p_cfg,size9);
	DMAC_Init();
	DMAC2_Init();
	DMAC3_Init();
	DMAC8_Init();
	DMAC9_Init();
	ADC_Init();
	pwm_init();	
	R_GPT_Open(&pwm_ctrl,&pwm_cfg);
	R_GPT_Start(&pwm_ctrl);
	R_GPT_Open(&time0_ctrl,&time0_cfg);
	R_GPT_Start(&time0_ctrl);
	gpt0_init();
	R_SCI_SPI_Open(&g_spi0_ctrl, &g_spi0_cfg);
  R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
	ceshi = ds18b20_init();
	while(1){	
		//pwm_setduty(1700, 1400);
			analyze_chuli();
			memset(analyze,0,sizeof(analyze));
			MY_data = Read_adc_value();
			DHT11_Read();
			temp = temp_integer;
			humi = humdity_integer;
			if(GPS_LNG_USE!=0.00){
				printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"X\":{\"value\":%.6f}}}",GPS_LNG_USE);
			}
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			if(GPS_LAT_USE!=0.00){
				printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"Y\":{\"value\":%.6f}}}",GPS_LAT_USE);
			}
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"dht11\":{\"value\":%f}}}",temp);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"humidity\":{\"value\":%f}}}",humi);

			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"imu_z\":{\"value\":%.0f}}}",angle.angleZ);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"PH\":{\"value\":%.3f}}}",MY_data.PH_value);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"conductivity\":{\"value\":%.2f}}}",MY_data.TDS_value);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"turbidity\":{\"value\":%.2f}}}",MY_data.TS300B_value);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
			printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"aaa\":{\"value\":%.2f}}}",MY_data.YANG_value);
			R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
//		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_04_PIN_06   , 1);
//	pwm_setduty(1500,1500);
			R_BSP_SoftwareDelay(1000,BSP_DELAY_UNITS_MILLISECONDS);
//	pwm_setduty(2000,1500);
//	 R_GPT_DutyCycleSet(&pwm_ctrl,57753,GPT_IO_PIN_GTIOCA);//上下
//	 R_GPT_DutyCycleSet(&pwm_ctrl,57753,GPT_IO_PIN_GTIOCB);//左右
//		R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
//			 R_GPT_DutyCycleSet(&pwm_ctrl,60000,GPT_IO_PIN_GTIOCA);//上下
//	 R_GPT_DutyCycleSet(&pwm_ctrl,60000,GPT_IO_PIN_GTIOCB);//左右
//		R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
	// R_GPT_DutyCycleSet(&pwm_ctrl,54632,GPT_IO_PIN_GTIOCA);//上下
//	 R_GPT_DutyCycleSet(&pwm_ctrl,54632,GPT_IO_PIN_GTIOCB);//左右
		R_BSP_SoftwareDelay(500,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_AllRed();
//			R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_AllCyan();
//			R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_AllPurple();
//			R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_AllGreen();
//			R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_AllWhite();
//			R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
// WS2812_StaticMultiColor();
//		R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
//		WS2812_AllOff();
//		R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
//		WS2812_AllGreen();
///		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_05_PIN_03, BSP_IO_LEVEL_LOW);
////	//	printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"PH\":{\"value\":%.3f}}}",11.11);
////	R_BSP_SoftwareDelay(1000 ,BSP_DELAY_UNITS_MILLISECONDS);
////		printf("{\"id\":\"123\",\"version\":\"1.0\",\"params\":{\"aaa\":{\"value\":[");
////		for(int i = 0; i < 18; i++) {
////    // 打印当前数值
////    printf("%d", N10_data[i]); // 或者 *(p+i)
////    
////    // 如果不是最后一个数，打印逗号分隔
////    if(i < 17) {
////        printf(",");
////    }
////}
////printf("]}}}"); // 注意这里闭合的是中括号 ] 和大括号 }}
//		
//		R_BSP_SoftwareDelay(2,BSP_DELAY_UNITS_SECONDS);
//  	R_BSP_SoftwareDelay(100,BSP_DELAY_UNITS_MILLISECONDS);
//		DHT11_Read();
//		R_BSP_SoftwareDelay(2,BSP_DELAY_UNITS_SECONDS);
//		R_BSP_SoftwareDelay(2000,BSP_DELAY_UNITS_MILLISECONDS);
//		printf("%f",gyro.gyroZ);
//		my_data = Read_adc_value();
//	//	printf("%d",gyro.gyroZ);
////		R_SCI_UART_Write(&g_uart7_ctrl,sci_rx_data,sizeof(sci_rx_data));
////		R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);
}
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD  

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
